export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const MATCH_SUGGESTIONS = 'MATCH_SUGGESTIONS';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RESET_APP_STATE = 'RESET_APP_STATE';
