export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const MATCH_SUGGESTIONS = 'MATCH_SUGGESTIONS';
export const UPDATE_INPUT = 'UPDATE_INPUT';
