const INITIAL_STATE = [
  'College Avenue, Tuguegarao City',
'A Soriano Street, Tuguegarao City',
'Adducul Street, Tuguegarao City',
'Aguinaldo Street, Tuguegarao City',
'Andrews Street, Tuguegarao City',
'Aquino Street, Tuguegarao City',
'Arellano Street, Tuguegarao City',
'Badaje Street, Tuguegarao City',
'Bagay Road, Tuguegarao City',
'Balzain Highway, Tuguegarao City',
'Balzain Road, Tuguegarao City',
'Bassig Street, Tuguegarao City',
'Blumentritt Street, Tuguegarao City',
'Bonifacio Street, Tuguegarao City',
'Buntun Highway, Tuguegarao City',
'Burgos Street, Tuguegarao City',
'Campos Street, Tuguegarao City',
'Capatan, Tuguegarao City',
'Carig Regional Center, Tuguegarao City',
'Caritan Highway, Tuguegarao City',
'CSU Road, Tuguegarao City',
'Del Rosario Street, Tuguegarao City',
'Diversion Road, Tuguegarao City',
'E Panaga Street, Tuguegarao City',
'Enrile Avenue, Tuguegarao City',
'Gomez Street, Tuguegarao City',
'Gonzaga Street, Tuguegarao City',
'Gunnacao Street, Tuguegarao City',
'Kalaw Street, Tuguegarao City',
'Larion Alto road, Tuguegarao City',
'Larion Bajo road, Tuguegarao City',
'Lecaros Street, Tuguegarao City',
'Legazpi Street, Tuguegarao City',
'Liban Street, Tuguegarao City',
'Linao-Carig Road, Tuguegarao City',
'Luna Street, Tuguegarao City',
'Mabini Street, Tuguegarao City',
'Magallanes Street, Tuguegarao City',
'Maggay Street, Tuguegarao City',
'Main Avenue, Tuguegarao City',
'Malilin Street, Tuguegarao City',
'Pallua Road, Tuguegarao City',
'Pallua-Buntun Highway, Tuguegarao City',
'R Soriano Street, Tuguegarao City',
'Reyno Street, Tuguegarao City',
'Rizal Street, Tuguegarao City',
'San Gabriel, Tuguegarao City',
'Taft Street, Tuguegarao City',
'Washington Street, Tuguegarao City',
];

export default (state = INITIAL_STATE, action) => {
    switch (action.type) {
        default:
            return state;
    }
};
